baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Hackeria"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"
  description = "Latinx is Cybersecurity"

  [params.home]
    avatarURL = "/hackeria_logo.png"
    
  [params.header]
    logo = "/static/hackeria_logo.png"
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
      [params.header.title]
        logo = "/hackeria_logo.png"

      [params.home.profile]
        avatarURL = "/hackeria_logo.png"
        subtitle = "Latinx in Cybersecurity"
        social = true
  
  [params.social]
    Slack = "thehackeria"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

